language: php
php:
  - "5.4"
services:
  - mysql
before_script:
  # get the latest frontaccounting code
  # - git -C htdocs pull origin master-cp
  # install npm deps and gulp
  - npm install -g gulp
  - npm install
  # - webdriver-manager update
  - ./node_modules/protractor/bin/webdriver-manager start &
  - sleep 5
  - php -S localhost:8000 -t htdocs &
  - sleep 1
  # db setup
  - mysql -e 'create database fa_test;'
    # Should be good to do gulp from here on
  - sleep 3
script:
  - gulp test-e2e-travis

